name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    # 환경 비밀(Environment secrets)을 사용하려면 환경을 명시해야 합니다.
    # 스크린샷처럼 github-pages 환경에 비밀을 넣었다면, build 잡에도 동일 환경을 지정하세요.
    environment: github-pages
    runs-on: ubuntu-latest
    env:
      # Actions Variables(권장) 또는 Secrets 중 하나에 설정하세요.
      # Settings → Secrets and variables → Actions → Variables/Secrets
      VITE_SUPABASE_URL: ${{ vars.VITE_SUPABASE_URL || secrets.VITE_SUPABASE_URL }}
      VITE_SUPABASE_ANON_KEY: ${{ vars.VITE_SUPABASE_ANON_KEY || secrets.VITE_SUPABASE_ANON_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Pages
        # Pages 배포 준비 (권장)
        uses: actions/configure-pages@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Verify required env
        run: |
          test -n "$VITE_SUPABASE_URL" || { echo "VITE_SUPABASE_URL is missing. Set it in Actions Variables or Secrets." >&2; exit 1; }
          test -n "$VITE_SUPABASE_ANON_KEY" || { echo "VITE_SUPABASE_ANON_KEY is missing. Set it in Actions Variables or Secrets." >&2; exit 1; }

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Add SPA fallback (404.html)
        # SPA 새로고침/직접 URL 진입 시 404 방지
        run: cp dist/index.html dist/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
